name: "Runs Linters and comment on PR"
description: "Runs Linters and comment on PR"

branding:
  color: yellow
  icon: check-square

inputs:
  linters:
    description: "List of linters to use"
    default: "a"
    required: true
  flake_parameters:
    description: "Another flake parameters"
    default: "b"
    required: false

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: pip install PyGithub
      shell: bash

    - run: python linters.py
      shell: bash
      env:
        INPUT_LINTERS: ${{ inputs.linters }}


